name: ci-lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: flake8
      run: |
        flake8 src/
    - name: black
      uses: psf/black@stable
    - name: MyPy
      run: |
        mypy src/
    - name: UnitTests
      run : |
        pytest -v
